[project]
name = "smallm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tiktoken>=0.12.0",
    "wandb>=0.22.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
